### ISSUE TITLE
The chrome extension cannot work properly on Microsoft Chromium Edge

### ISSUE THREAD

**Issue by francisafu** [AndrewBastin/postwoman-extension#4]
Hi, 
I use Microsoft Chromium Edge, and after I install this extension from Chrome Webstore, It cannot work properly . Please fix this, thanks!

**Comment by AndrewBastin** [comment]
Thanks for opening the issue!


The browser extension hasn't so far been tested on Edge, I think it's about time I look into it.

I will look into it ASAP.

**Comment by AndrewBastin** [comment]
@francisafu I just tested the extension with the new Microsoft Edge and to me, everything looks fine and everything works.

Can you tell me if the newest build works on Microsoft Edge or tell me what specific things didn't work ?

Closing for now.
