### ISSUE TITLE
Not an Issue! ask for howto instead (addon for ff)

### ISSUE THREAD

**Issue by fabrice-regnier** [AndrewBastin/postwoman-extension#5]
Hello,

I'm very sorry for my ignorance but when i install the addon postwoman to firefox 68.7.0esr (64 bits), Linux debian, none icon appears nowhere. It is normal ? i see nothing when i go into the web dev menu. What is the right way to use postwoman ? 
by the way, i love the name ;)
Thank you and regards,
f.
ps: sorry for posting in github/issues, i saw no forum.

**Comment by AndrewBastin** [comment]
Hi there,

It is fine to ask questions here. (at least for me ^_^)

And the answer to your question is: Yes, this is normal. The extension runs in the background in your browser when you visit [https://postwoman.io](https://postwoman.io) and it works in the background to route your requests through it.
