### ISSUE TITLE
Question: how to verify the extension is working properly?

### ISSUE THREAD

**Issue by cougil** [AndrewBastin/postwoman-extension#6]
Hi!

I'd like to verify how the extension is working, because I already installed it and after browsing for a while, I haven't seen any requests arriving to postwoman.io

First question probably, do I need to be logged in Github or Google to make it work properly?

Best,

**Comment by AndrewBastin** [comment]
Hi @cougil ,

Well, you can verify that extension is hooking with Postwoman by running Postwoman and opening up the log.

There should be a log message `Connected to Postwoman Browser Extension vX.x` indicating a successful hook.

No, you don't need to be logged in for the extension to work.

I didn't understand what you meant by "I haven't seen any requests arriving to postwoman.io", when the extension is installed, Postwoman routes the Network Requests to the extension and the extension makes the actual request, hence it won't be visible in the Network Tab in DevTools.

If you are getting Network Errors or are not able to see requests even after installing the extension, then please report that.

Thank you!

**Comment by cougil** [comment]
Thank you @AndrewBastin for your answer.

Just to clarify: I downloaded the Extension (Chrome) and I was expecting to catch/see the requests my browser could make when I browse around the web. I understand that the extension should grab all the requests and therefore I should be able to see all of them appearing there. Is this what this extension does or only records whatever request I send but **only** when I'm connected to "postwoman.io"? Because it is the last one, then it is not exactly what I was looking for ;-) 

Best,

**Comment by AndrewBastin** [comment]
Well, yes, as a security measure, the extension from the Web Store and AMO only hooks to the official Postwoman URLs. (check manifest.json). If you want it to work with the other URLs, you can add your own URLs to manifest.json and use the extension that way.
