### ISSUE TITLE
Extension do not work properly on Brave

### ISSUE THREAD

**Issue by unggulzmalqp** [AndrewBastin/postwoman-extension#8]
Hello, I would like to raise an issue.
When I open postwoman.io with the extension installed, it cannot complete the request, just loading.
![image](https://user-images.githubusercontent.com/16437339/86124322-28164480-bb05-11ea-8a65-afd56d518555.png)

On the console, it says something like this:
![image](https://user-images.githubusercontent.com/16437339/86124419-4ed47b00-bb05-11ea-8555-3ff7a42f2b02.png)

Browser version:
Version 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)

**Comment by AndrewBastin** [comment]
Hi there, sorry about that, there was a small bug with the published version right now, I have uploaded a version with the bug fixed but Chrome Web Store hasn't finished reviewing it.

**Comment by unggulzmalqp** [comment]
Oh, okay then
